steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/adk/adk-web-ui-agent-bug-assist:latest'
  - '.'
  - '--file'
  - 'Dockerfile'
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/adk/adk-web-ui-agent-bug-assist:latest'
