[project]
name = "gemma-adk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=1.17.0",
    "a2a-sdk>=0.3.11",
    "google-genai>=1.27.0",
    "litellm>=1.74.8",
    "python-dotenv>=1.1.1",
    "toolbox-core==0.5.2",
]
